set_property IOSTANDARD LVCMOS18 [get_ports {GPO1_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN E5 [get_ports {GPO1_0[0]}]
set_property PACKAGE_PIN A6 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN D5 [get_ports uart_rtl_0_rxd]
